sudo: false
language: node_js
node_js:
  - 9.11.1
branches:
  only:
    - master
before_install:
  - npm i -g npm@6.0.1
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run prod
deploy:
  provider: heroku
  app: "tinyscrap"
  api_key:
    secure: "0003baca-4f5a-4c62-a81b-4c1711e9d6b5"